version: '3'
networks: 
  default_stack:
services:
    prom: 
      networks: 
        - default_stack
      image: prom/prometheus
      ports:
        - 9090:9090
      volumes:
        - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        - /data/prometheus:/data/prometheus 
     
      command:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--storage.tsdb.path=/data/prometheus"
      deploy:    
        mode: replicated
        replicas: 3
    
    node_exporter:
          networks: 
            - default_stack
          image: prom/node-exporter
          ports:
            - 9100:9100
          deploy:    
            mode: global
            
          
    grafana:
      image: grafana/grafana
      user: "1000"
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=secure_pass
      volumes:
        - ./grafana_db:/var/lib/grafana
      depends_on:
        - prometheus
      ports:
        - '3000:3000'
        
      

             

            



