version: "3.6"
networks: 
  default_stack:
services:
  elasticsearch:
    networks: 
      - default_stack
    image: registry.nasri.local:5000/elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports: 
      - "9200:9200"
  kibana:
    networks: 
      - default_stack
    image: registry.nasri.local:5000/kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
  logstash:
    networks: 
      - default_stack
    image: registry.nasri.local:5000/logstash
    ports:
      - "12201:12201/udp"
    depends_on:
      - elasticsearch
    deploy:
      mode: global
    volumes:
      - logstash-pipeline:/usr/share/logstash/pipeline/
volumes:
  esdata:
    driver: local
  logstash-pipeline:
    driver: local