---
- name: Deploy web and nginx  on swarm cluster 
  vars_files: ./vars/default.yml
  hosts: all
  tasks: 
     - name : pull source codes from git repository 
       git: 
          repo: 'https://github.com/sysnasri/dotin'
          dest: /var/swarm/dotin
          update: yes
  

     - name: Deploy stack from a compose file
       docker_stack:
        state: present
        name: web_stack
        compose:
          - /var/swarm/dotin/Web/docker-compose.yml
       when: "{{ inventory_hostname == 'node1' }}"  


