version: "3.3"
networks: 
    default_stack:
services:
  db:   
        
        networks: 
            - default_stack
        image: registry.nasri.local:5000/mysql:v1    
        build:
             context: './mysql'
        environment:
            MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_password
            MYSQL_DATABASE: wp_test
            MYSQL_USER: wpuser
            MYSQL_PASSWORD: wpuserpw
        secrets: 
            - mysql_root_password    
        ports:
          - "3306:3306"
        volumes:
             - ./mysql:/var/lib/mysql

        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.role == manager

  loadbalancer:
        networks: 
            - default_stack
        image: registry.nasri.local:5000/loadbalancer:v1      
        build:
            context: './loadbalancer'
        ports:
            - "80:80"
        volumes:

            - ./loadbalancer/nginx-site.conf:/etc/nginx/conf.d/nginx-site.conf

        deploy:
            mode: replicated
            replicas: 3
                
  nginx:
        networks: 
            - default_stack
        image: registry.nasri.local:5000/nginx:v1                   
        build:
            context: './nginx'
        ports:
            - "8888:80"
        volumes:
            - ./code:/var/www/html
            - ./nginx/nginx-site.conf:/etc/nginx/conf.d/nginx-site.conf
        deploy:
            mode: replicated
            replicas: 3


  php-fpm:
        networks: 
          - default_stack
        image: registry.nasri.local:5000/php-fpm:v1    
        build:
            context: './php'
        ports:
            - "9000:9000"
        volumes:
            - ./code:/var/www/html
            - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        deploy:
            mode: replicated
            replicas: 3
secrets: 
    mysql_root_password:
        file: /root/mysql_root_password
